services:
  tctctoe-api-svc:
    container_name: tctctoe-api
    image: danielpenado/tctctoe-api
    ports:
      - "8080:8080"
    restart: always
    environment:
      - sec_key=tctc_key
    networks:
      - tctctoe-net

  tctctoe-ui-svc:
    container_name: tctctoe-ui
    image: danielpenado/tctctoe-ui
    ports:
      - "80:80"
    restart: always
    depends_on:
      - tctctoe-api-svc
    networks:
      - tctctoe-net
  
networks:
  tctctoe-net:
